#!/usr/bin/env python3
"""Post-process the rendered Alertmanager configuration.

Run by ``scripts/lib/render.sh`` immediately after ``render.py``.

Why this is needed
------------------
E-mail notification is optional (CDC annexe D: ``SMTP_HOST`` and
``ALERT_EMAIL_TO`` may be empty). But Alertmanager **refuses to start** on an
``email_configs`` entry with an empty ``to``::

    FAILED: missing to address in email config

and a receiver pointing at ``:25`` would fail every notification, which would
fire ``AlertmanagerNotificationsFailing`` permanently — the monitoring stack
alerting about its own unused optional feature.

So the base file declares the e-mail route and receiver in full, and this
script **removes** them when SMTP is not configured. Removing rather than
appending keeps ``config/alertmanager/alertmanager.yml`` a complete, valid,
lintable document that a reader can understand on its own.

    render-alertmanager.py <rendered-file>
"""

from __future__ import annotations

import os
import sys

import yaml


def smtp_configured() -> bool:
    """SMTP counts as configured only when BOTH ends are set."""
    return bool(os.environ.get("SMTP_HOST", "").strip()) and bool(
        os.environ.get("ALERT_EMAIL_TO", "").strip()
    )


def strip_email(doc: dict) -> dict:
    """Remove the e-mail route and receiver, and the now-useless SMTP globals."""
    receivers = doc.get("receivers") or []
    doc["receivers"] = [r for r in receivers if r.get("name") != "email"]

    route = doc.get("route") or {}
    routes = route.get("routes") or []
    route["routes"] = [r for r in routes if r.get("receiver") != "email"]

    # Leaving `smtp_smarthost: ":25"` behind would be misleading in an
    # operator's `amtool config show`.
    for key in ("smtp_smarthost", "smtp_from", "smtp_require_tls"):
        (doc.get("global") or {}).pop(key, None)

    return doc


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit("usage: render-alertmanager.py <rendered-file>")
    path = sys.argv[1]

    with open(path, encoding="utf-8") as handle:
        doc = yaml.safe_load(handle)

    if smtp_configured():
        print("  alertmanager: SMTP configured, the email receiver is kept")
    else:
        doc = strip_email(doc)
        print("  alertmanager: SMTP not configured, email route and receiver removed")

    with open(path, "w", encoding="utf-8") as handle:
        handle.write(
            "---\n"
            "# Generated from config/alertmanager/alertmanager.yml by\n"
            "# scripts/lib/render-alertmanager.py — do not edit this file.\n"
        )
        yaml.safe_dump(doc, handle, sort_keys=False, allow_unicode=True, width=100)
    return 0


if __name__ == "__main__":
    sys.exit(main())
