#!/usr/bin/env bash
# =============================================================================
# `make certs` (2/2) — Elasticsearch transport certificates.
#
# What they are for
# -----------------
# ADR-0007: the Elasticsearch HTTP API stays in clear text, confined to the
# `data` overlay (internal + IPsec-encrypted). The **transport** protocol —
# node-to-node replication and cluster state — is a different matter:
# `xpack.security.transport.ssl.enabled=true` is mandatory as soon as security
# is on, and it authenticates the nodes to each other. A node without a valid
# certificate signed by the cluster CA simply cannot join.
#
# One CA + one certificate per node (es-1, es-2, es-3). Each SAN carries the
# Swarm service name, because that is the name the peers resolve
# (`discovery.seed_hosts=es-1,es-2,es-3`).
#
# Generation method
# -----------------
# Primary: `elasticsearch-certutil` from the official image (CDC §7.4), which
# produces exactly what the distribution expects.
# Fallback: openssl, when the image cannot be pulled (air-gapped workstation,
# blocked registry). The result is equivalent — a PEM CA and three PEM
# key/cert pairs with the right EKUs — and the script says which path it took.
#
#   scripts/gen-es-certs.sh            generate what is missing
#   scripts/gen-es-certs.sh --force    regenerate everything (rolling restart!)
# =============================================================================
set -Eeuo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/lib/common.sh"

need_cmd openssl
load_env

FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

readonly ES_CERTS="${DW_CERTS_DIR}/es"
readonly ES_DAYS=1825          # 5 years: an internal, node-to-node PKI
readonly ES_IMAGE="docker.elastic.co/elasticsearch/elasticsearch:8.19.21"
readonly -a ES_NODES=(es-1 es-2 es-3)

mkdir -p "$ES_CERTS"
chmod 700 "$ES_CERTS"

if [[ -f "${ES_CERTS}/ca.crt" && $FORCE -eq 0 ]]; then
  ok "Elasticsearch certificates already present in ${ES_CERTS}/"
else
  section "Elasticsearch transport certificates"

  # --- Path 1: elasticsearch-certutil ---------------------------------------
  # `docker run --rm` on the official image: no ES service is needed, certutil
  # is a standalone CLI shipped inside it.
  use_certutil=0
  if docker image inspect "$ES_IMAGE" >/dev/null 2>&1 \
     || docker pull --quiet "$ES_IMAGE" >/dev/null 2>&1; then
    use_certutil=1
  fi

  if (( use_certutil )); then
    info "using elasticsearch-certutil (${ES_IMAGE})"
    # `--pem` yields PEM rather than the PKCS#12 default: PEM is what the
    # Docker secrets carry and what the stack mounts.
    cat > "${ES_CERTS}/instances.yml" <<EOF
# Generated by scripts/gen-es-certs.sh — do not edit.
instances:
$(for n in "${ES_NODES[@]}"; do
    printf '  - name: "%s"\n    dns: ["%s", "localhost"]\n    ip: ["127.0.0.1"]\n' "$n" "$n"
  done)
EOF
    docker run --rm -u 0 -v "${ES_CERTS}:/certs" "$ES_IMAGE" \
      bash -c '
        set -e
        cd /certs
        rm -rf ca ca.zip certs.zip es-1 es-2 es-3
        elasticsearch-certutil ca --pem --silent --out ca.zip
        unzip -q -o ca.zip
        elasticsearch-certutil cert --pem --silent \
          --in instances.yml --out certs.zip \
          --ca-cert ca/ca.crt --ca-key ca/ca.key
        unzip -q -o certs.zip
        rm -f ca.zip certs.zip
      ' >/dev/null
    cp "${ES_CERTS}/ca/ca.crt" "${ES_CERTS}/ca.crt"
    for n in "${ES_NODES[@]}"; do
      cp "${ES_CERTS}/${n}/${n}.crt" "${ES_CERTS}/${n}.crt"
      cp "${ES_CERTS}/${n}/${n}.key" "${ES_CERTS}/${n}.key"
    done
    ok "certificates generated by elasticsearch-certutil"
  else
    # --- Path 2: openssl fallback -------------------------------------------
    warn "${ES_IMAGE} unreachable — falling back to openssl"
    warn "the result is equivalent; note it in docs/04-composants/elasticsearch.md"

    openssl req -x509 -newkey rsa:4096 -sha256 -days "$ES_DAYS" -nodes \
      -keyout "${ES_CERTS}/ca.key" -out "${ES_CERTS}/ca.crt" \
      -subj "/C=FR/O=Dockerwarts/OU=Elasticsearch/CN=Dockerwarts ES Transport CA" \
      -addext "basicConstraints=critical,CA:TRUE,pathlen:0" \
      -addext "keyUsage=critical,keyCertSign,cRLSign" 2>/dev/null
    chmod 600 "${ES_CERTS}/ca.key"

    for n in "${ES_NODES[@]}"; do
      cat > "${ES_CERTS}/${n}.cnf" <<EOF
[req]
distinguished_name = dn
req_extensions     = v3_req
prompt             = no
[dn]
C  = FR
O  = Dockerwarts
OU = Elasticsearch
CN = ${n}
[v3_req]
basicConstraints = critical,CA:FALSE
keyUsage         = critical,digitalSignature,keyEncipherment
# Both serverAuth and clientAuth: on the transport protocol a node is a server
# for its peers and a client of theirs at the same time.
extendedKeyUsage = serverAuth,clientAuth
subjectAltName   = @alt
[alt]
DNS.1 = ${n}
DNS.2 = localhost
IP.1  = 127.0.0.1
EOF
      openssl req -new -newkey rsa:2048 -sha256 -nodes \
        -keyout "${ES_CERTS}/${n}.key" -out "${ES_CERTS}/${n}.csr" \
        -config "${ES_CERTS}/${n}.cnf" 2>/dev/null
      openssl x509 -req -in "${ES_CERTS}/${n}.csr" \
        -CA "${ES_CERTS}/ca.crt" -CAkey "${ES_CERTS}/ca.key" -CAcreateserial \
        -out "${ES_CERTS}/${n}.crt" -days "$ES_DAYS" -sha256 \
        -extfile "${ES_CERTS}/${n}.cnf" -extensions v3_req 2>/dev/null
      rm -f "${ES_CERTS}/${n}.csr"
      chmod 600 "${ES_CERTS}/${n}.key"
      chmod 644 "${ES_CERTS}/${n}.crt"
    done
    ok "certificates generated by openssl"
  fi
fi

# =============================================================================
# Verification — every node certificate must chain to the CA and carry its own
# service name in the SAN, otherwise the node silently fails to join.
# =============================================================================
section "Verification"
for n in "${ES_NODES[@]}"; do
  openssl verify -CAfile "${ES_CERTS}/ca.crt" "${ES_CERTS}/${n}.crt" >/dev/null \
    || die "${n}: the certificate does not validate against the CA"
  openssl x509 -in "${ES_CERTS}/${n}.crt" -noout -text | grep -q "DNS:${n}" \
    || die "${n}: '${n}' is missing from the SAN — the node could not join the cluster"
  ok "${n}: valid, SAN contains ${n}"
done

# =============================================================================
# Docker secrets
# =============================================================================
section "Docker secrets"
if ! docker info --format '{{.Swarm.ControlAvailable}}' 2>/dev/null | grep -q true; then
  warn "not on a Swarm manager: the files are in ${ES_CERTS}/, the secrets are not created"
  exit 0
fi

create_secret() {
  local name=$1 file=$2
  if docker secret inspect "$name" >/dev/null 2>&1; then
    log "${name}: already present"
    return 0
  fi
  docker secret create "$name" "$file" >/dev/null
  ok "${name}"
}

create_secret dw_es_ca "${ES_CERTS}/ca.crt"
for i in 1 2 3; do
  create_secret "dw_es_cert_${i}" "${ES_CERTS}/es-${i}.crt"
  create_secret "dw_es_key_${i}"  "${ES_CERTS}/es-${i}.key"
done
