#!/usr/bin/env bash
# =============================================================================
# `make certs` (1/2) — internal CA and the `*.${DOMAIN}` wildcard certificate.
#
# Why an internal CA rather than ACME
# -----------------------------------
# `dockerwarts.lan` is not a real domain: no public CA can validate it, and
# there is no DNS server in the lab. An internal CA gives real TLS (the client
# validates a chain, the cipher suites are modern, HSTS is meaningful) with a
# single trust anchor to distribute. Switching to Let's Encrypt DNS-01 for a
# real domain is a Traefik configuration change only — documented in
# docs/04-composants/traefik.md.
#
# Produces, in certs/ (git-ignored):
#   ca.key  ca.crt        the CA — ca.key NEVER leaves this host
#   wildcard.key/.crt     *.${DOMAIN} + ${DOMAIN} + the VIP in SAN
#   fullchain.crt         wildcard + CA, what Traefik serves
#
# and the Docker secrets dw_ca_cert, dw_tls_cert, dw_tls_key.
#
# Idempotent: existing, still-valid certificates are left alone.
#   --force   regenerate the leaf certificate (keeps the CA)
#   --force-ca regenerate everything, CA included (re-trust every client)
# =============================================================================
set -Eeuo pipefail
source "$(dirname -- "${BASH_SOURCE[0]}")/lib/common.sh"

need_cmd openssl
load_env

FORCE_LEAF=0
FORCE_CA=0
case "${1:-}" in
  --force)    FORCE_LEAF=1 ;;
  --force-ca) FORCE_LEAF=1; FORCE_CA=1 ;;
  "")         ;;
  *)          die "usage: $0 [--force | --force-ca]" ;;
esac

readonly CA_DAYS=3650     # 10 years: the CA is distributed once to the clients
readonly LEAF_DAYS=825    # 825 days is the maximum browsers accept for a leaf
readonly CERTS="$DW_CERTS_DIR"

mkdir -p "$CERTS"
chmod 700 "$CERTS"

# =============================================================================
# 1. Internal certificate authority
# =============================================================================
section "Internal certificate authority"
if [[ -f "${CERTS}/ca.crt" && -f "${CERTS}/ca.key" && $FORCE_CA -eq 0 ]]; then
  ok "CA already present ($(openssl x509 -in "${CERTS}/ca.crt" -noout -enddate | cut -d= -f2))"
else
  # -pkeyopt rsa_keygen_bits:4096 — the CA outlives the leaves by far.
  openssl req -x509 -newkey rsa:4096 -sha256 -days "$CA_DAYS" -nodes \
    -keyout "${CERTS}/ca.key" -out "${CERTS}/ca.crt" \
    -subj "/C=FR/O=Dockerwarts/OU=Infrastructure/CN=Dockerwarts Internal CA" \
    -addext "basicConstraints=critical,CA:TRUE,pathlen:0" \
    -addext "keyUsage=critical,keyCertSign,cRLSign" \
    -addext "subjectKeyIdentifier=hash" \
    2>/dev/null
  chmod 600 "${CERTS}/ca.key"
  chmod 644 "${CERTS}/ca.crt"
  ok "CA created, valid ${CA_DAYS} days"
fi

# =============================================================================
# 2. Wildcard certificate
#
# SAN content, and why each entry is there:
#   *.${DOMAIN}   every published UI (glpi., grafana., kibana., …)
#   ${DOMAIN}     the apex, so that a bare https://dockerwarts.lan still works
#   vip.${DOMAIN} explicit name of the entry point
#   IP:${VIP}     lets an operator hit https://192.168.56.10 without a name;
#                 the blackbox exporter also probes the VIP by address
#   IP:127.0.0.1 / localhost   the Traefik healthcheck and Keepalived's
#                 chk_traefik talk to the local instance
# =============================================================================
section "Wildcard certificate *.${DOMAIN}"
if [[ -f "${CERTS}/wildcard.crt" && $FORCE_LEAF -eq 0 ]] \
   && openssl x509 -in "${CERTS}/wildcard.crt" -noout -checkend $((30 * 86400)) >/dev/null 2>&1; then
  ok "certificate already present and valid for more than 30 days"
else
  cat > "${CERTS}/wildcard.cnf" <<EOF
# Generated by scripts/gen-certs.sh — do not edit.
[req]
distinguished_name = dn
req_extensions     = v3_req
prompt             = no

[dn]
C  = FR
O  = Dockerwarts
OU = Infrastructure
CN = *.${DOMAIN}

[v3_req]
basicConstraints = critical,CA:FALSE
keyUsage         = critical,digitalSignature,keyEncipherment
extendedKeyUsage = serverAuth,clientAuth
subjectAltName   = @alt_names

[alt_names]
DNS.1 = *.${DOMAIN}
DNS.2 = ${DOMAIN}
DNS.3 = localhost
IP.1  = ${VIP}
IP.2  = 127.0.0.1
EOF

  openssl req -new -newkey rsa:2048 -sha256 -nodes \
    -keyout "${CERTS}/wildcard.key" -out "${CERTS}/wildcard.csr" \
    -config "${CERTS}/wildcard.cnf" 2>/dev/null

  openssl x509 -req -in "${CERTS}/wildcard.csr" \
    -CA "${CERTS}/ca.crt" -CAkey "${CERTS}/ca.key" -CAcreateserial \
    -out "${CERTS}/wildcard.crt" -days "$LEAF_DAYS" -sha256 \
    -extfile "${CERTS}/wildcard.cnf" -extensions v3_req 2>/dev/null

  # Traefik is given the full chain: a client that only trusts the CA still
  # builds the path, and `curl --cacert ca.crt` validates without -k.
  cat "${CERTS}/wildcard.crt" "${CERTS}/ca.crt" > "${CERTS}/fullchain.crt"
  chmod 600 "${CERTS}/wildcard.key"
  chmod 644 "${CERTS}/wildcard.crt" "${CERTS}/fullchain.crt"
  rm -f "${CERTS}/wildcard.csr"
  ok "certificate created, valid ${LEAF_DAYS} days"
fi

# =============================================================================
# 3. Self-verification — the chain must actually validate
# =============================================================================
section "Verification"
openssl verify -CAfile "${CERTS}/ca.crt" "${CERTS}/wildcard.crt" >/dev/null \
  || die "the certificate does not validate against the CA"
ok "chain valid"

# The private key and the certificate must be a pair: a mismatch only shows up
# as an opaque TLS handshake failure at runtime.
key_mod="$(openssl rsa  -in "${CERTS}/wildcard.key" -noout -modulus 2>/dev/null | openssl sha256)"
crt_mod="$(openssl x509 -in "${CERTS}/wildcard.crt" -noout -modulus 2>/dev/null | openssl sha256)"
[[ "$key_mod" == "$crt_mod" ]] || die "the key and the certificate do not match"
ok "key ↔ certificate pair consistent"

openssl x509 -in "${CERTS}/wildcard.crt" -noout -text \
  | grep -A1 'Subject Alternative Name' | tail -1 | sed 's/^ */    SAN: /' >&2

# =============================================================================
# 4. Docker secrets
# =============================================================================
section "Docker secrets"
if ! docker info --format '{{.Swarm.ControlAvailable}}' 2>/dev/null | grep -q true; then
  warn "not on a Swarm manager: the files are in ${CERTS}/, the secrets are not created"
  exit 0
fi

create_secret() {
  local name=$1 file=$2
  if docker secret inspect "$name" >/dev/null 2>&1; then
    log "${name}: already present"
    return 0
  fi
  docker secret create "$name" "$file" >/dev/null
  ok "${name}"
}
create_secret dw_ca_cert  "${CERTS}/ca.crt"
create_secret dw_tls_cert "${CERTS}/fullchain.crt"
create_secret dw_tls_key  "${CERTS}/wildcard.key"

if [[ -f "${DW_SECRETS_DIR}/dw_traefik_htpasswd.txt" ]]; then
  create_secret dw_traefik_htpasswd "${DW_SECRETS_DIR}/dw_traefik_htpasswd.txt"
fi

cat >&2 <<EOF

To validate from the workstation without -k:
  curl --cacert ${CERTS}/ca.crt https://whoami.${DOMAIN}/

To trust the CA system-wide (Debian/Ubuntu):
  sudo cp ${CERTS}/ca.crt /usr/local/share/ca-certificates/dockerwarts.crt
  sudo update-ca-certificates
EOF
